version: "3"

services:

  # main db
  # -----------
  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    restart: always

  # create user
  # -----------
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:1.8.0
    container_name: influx_db_cli
    entrypoint: influx setup --username=admin --password=admin --host=http://influxdb:8086 -f
    depends_on:
      - influxdb

  # UPA 1st task
  # ------------
  scraper:
    build: .  # build Dockerfile
    container_name: scraper
    command: ["python", "scraper.py"] # execute this command
    links:
      - influxdb
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_LOGIN=admin
      - INFLUX_PASSWORD=admin


#  # UPA 2nd task
#  # ------------
#  visualizer:
#    extends:
#      service: base
#
#    container_name: visualizer
