version: "3"

services:

  # main db
  # -----------
  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
      - "8086:8086"
    # local path for creating persistent db
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    # setup credentials for user
    environment:
      INFLUXDB_HOSTNAME: "http://influxdb:8086"
      INFLUXDB_USERNAME: "upa21"
      INFLUXDB_PASSWORD: "upa21"
      # disable limit for client data size in 1 saving request
      INFLUXDB_HTTP_MAX_BODY_SIZE: 0
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
      INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
    restart: always

  # UPA 1st task
  # ------------
  scraper:
    build: .  # build Dockerfile
    container_name: scraper
    command: ["python", "scraper.py"] # execute this command
    environment:
      INFLUX_HOST: "influxdb"
      INFLUX_PORT: "8086"
      INFLUX_LOGIN: "upa21"
      INFLUX_PASSWORD: "upa21"

#  # UPA 2nd task
#  # ------------

  visualizer:
    build: .  # build Dockerfile
    container_name: visualizer
    user: "1000:1000" # $(id -u $USER):$(id -g $USER)
    command: ["python3", "visualizer.py"] # execute this command
    environment:
      INFLUX_HOST: "influxdb"
      INFLUX_PORT: "8086"
      INFLUX_LOGIN: "upa21"
      INFLUX_PASSWORD: "upa21"
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${LOCAL_PROJECT_DIR}:/app
